language: php

php:
 - '5.4'
 - '5.5'
 - '5.6'
 - '7.0'
 - '7.1'
 - '7.2'
 - hhvm # on Trusty only
 - nightly

# Commands to be run before your environment runs.
before_script:
 - composer self-update
 - composer update --no-interaction

# Commands you want to run that will verify your build.
script: ./phpunit --coverage-clover=coverage.xml

after_success:
 - bash <(curl -s https://codecov.io/bash)
